.TH "__main__.CameraConfig" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__main__.CameraConfig
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 869 of file __main__\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
