.TH "__main__.WebcamVideoStream" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__main__.WebcamVideoStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, camera, \fBcameraServer\fP, frameWidth, frameHeight, \fBname\fP='WebcamVideoStream')"
.br
.ti -1c
.RI "def \fBstart\fP (self)"
.br
.ti -1c
.RI "def \fBupdate\fP (self)"
.br
.ti -1c
.RI "def \fBread\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.ti -1c
.RI "def \fBgetError\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwebcam\fP"
.br
.ti -1c
.RI "\fBautoExpose\fP"
.br
.ti -1c
.RI "\fBprevValue\fP"
.br
.ti -1c
.RI "\fBimg\fP"
.br
.ti -1c
.RI "\fBstream\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBstopped\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file __main__\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __main__\&.WebcamVideoStream\&.__init__ ( self,  camera,  cameraServer,  frameWidth,  frameHeight,  name = \fC'WebcamVideoStream'\fP)"

.PP
Definition at line 98 of file __main__\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def __main__\&.WebcamVideoStream\&.getError ( self)"

.PP
Definition at line 169 of file __main__\&.py\&.
.SS "def __main__\&.WebcamVideoStream\&.read ( self)"

.PP
Definition at line 161 of file __main__\&.py\&.
.SS "def __main__\&.WebcamVideoStream\&.start ( self)"

.PP
Definition at line 124 of file __main__\&.py\&.
.SS "def __main__\&.WebcamVideoStream\&.stop ( self)"

.PP
Definition at line 165 of file __main__\&.py\&.
.SS "def __main__\&.WebcamVideoStream\&.update ( self)"

.PP
Definition at line 131 of file __main__\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "__main__\&.WebcamVideoStream\&.autoExpose"

.PP
Definition at line 109 of file __main__\&.py\&.
.SS "__main__\&.WebcamVideoStream\&.img"

.PP
Definition at line 112 of file __main__\&.py\&.
.SS "__main__\&.WebcamVideoStream\&.name"

.PP
Definition at line 118 of file __main__\&.py\&.
.SS "__main__\&.WebcamVideoStream\&.prevValue"

.PP
Definition at line 110 of file __main__\&.py\&.
.SS "__main__\&.WebcamVideoStream\&.stopped"

.PP
Definition at line 122 of file __main__\&.py\&.
.SS "__main__\&.WebcamVideoStream\&.stream"

.PP
Definition at line 114 of file __main__\&.py\&.
.SS "__main__\&.WebcamVideoStream\&.webcam"

.PP
Definition at line 103 of file __main__\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
