.TH "__main__.FPS" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__main__.FPS
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBstart\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.ti -1c
.RI "def \fBupdate\fP (self)"
.br
.ti -1c
.RI "def \fBelapsed\fP (self)"
.br
.ti -1c
.RI "def \fBfps\fP (self)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_start\fP"
.br
.ti -1c
.RI "\fB_end\fP"
.br
.ti -1c
.RI "\fB_numFrames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file __main__\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __main__\&.FPS\&.__init__ ( self)"

.PP
Definition at line 36 of file __main__\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def __main__\&.FPS\&.elapsed ( self)"

.PP
Definition at line 57 of file __main__\&.py\&.
.SS "def __main__\&.FPS\&.fps ( self)"

.PP
Definition at line 65 of file __main__\&.py\&.
.SS "def __main__\&.FPS\&.start ( self)"

.PP
Definition at line 43 of file __main__\&.py\&.
.SS "def __main__\&.FPS\&.stop ( self)"

.PP
Definition at line 48 of file __main__\&.py\&.
.SS "def __main__\&.FPS\&.update ( self)"

.PP
Definition at line 52 of file __main__\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "__main__\&.FPS\&._end\fC [private]\fP"

.PP
Definition at line 40 of file __main__\&.py\&.
.SS "__main__\&.FPS\&._numFrames\fC [private]\fP"

.PP
Definition at line 41 of file __main__\&.py\&.
.SS "__main__\&.FPS\&._start\fC [private]\fP"

.PP
Definition at line 39 of file __main__\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
