.TH "__main__.VideoShow" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__main__.VideoShow
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, imgWidth, imgHeight, \fBcameraServer\fP, \fBframe\fP=None)"
.br
.ti -1c
.RI "def \fBstart\fP (self)"
.br
.ti -1c
.RI "def \fBshow\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.ti -1c
.RI "def \fBnotifyError\fP (self, error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoutputStream\fP"
.br
.ti -1c
.RI "\fBframe\fP"
.br
.ti -1c
.RI "\fBstopped\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class that continuously shows a frame using a dedicated thread.

.fi
.PP
 
.PP
Definition at line 71 of file __main__\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __main__\&.VideoShow\&.__init__ ( self,  imgWidth,  imgHeight,  cameraServer,  frame = \fCNone\fP)"

.PP
Definition at line 76 of file __main__\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def __main__\&.VideoShow\&.notifyError ( self,  error)"

.PP
Definition at line 92 of file __main__\&.py\&.
.SS "def __main__\&.VideoShow\&.show ( self)"

.PP
Definition at line 85 of file __main__\&.py\&.
.SS "def __main__\&.VideoShow\&.start ( self)"

.PP
Definition at line 81 of file __main__\&.py\&.
.SS "def __main__\&.VideoShow\&.stop ( self)"

.PP
Definition at line 89 of file __main__\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "__main__\&.VideoShow\&.frame"

.PP
Definition at line 78 of file __main__\&.py\&.
.SS "__main__\&.VideoShow\&.outputStream"

.PP
Definition at line 77 of file __main__\&.py\&.
.SS "__main__\&.VideoShow\&.stopped"

.PP
Definition at line 79 of file __main__\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
