.TH "Arm" 3 "Mon Apr 8 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arm \- A subsystem that controls the \fBArm\fP of the robot\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Arm\&.h>\fP
.PP
Inherits Subsystem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArm\fP ()"
.br
.ti -1c
.RI "void \fBInitDefaultCommand\fP () override"
.br
.RI "Initalizes the default command for this subsystem (\fBArm\fP) "
.ti -1c
.RI "void \fBMoveArm\fP (double Speed)"
.br
.RI "Move \fBArm\fP arm up or down\&. "
.ti -1c
.RI "bool \fBGetSensor\fP (void)"
.br
.RI "Returns whether the hall effects is tripped This is the sensor for when the arm is lowered\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "can::WPI_TalonSRX * \fBpArmMotor\fP"
.br
.RI "Pointer for \fBArm\fP arm motor\&. "
.ti -1c
.RI "can::WPI_TalonSRX * \fBpArmMotor2\fP"
.br
.RI "Pointer for \fBArm\fP arm motor\&. "
.ti -1c
.RI "frc::DigitalInput * \fBpArmHall\fP"
.br
.RI "hall effects for arm is lowered enough "
.in -1c
.SH "Detailed Description"
.PP 
A subsystem that controls the \fBArm\fP of the robot\&. 
.PP
Definition at line 15 of file Arm\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Arm::Arm ()"

.PP
Definition at line 3 of file Arm\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Arm::GetSensor (void)"

.PP
Returns whether the hall effects is tripped This is the sensor for when the arm is lowered\&. 
.PP
\fBReturns:\fP
.RS 4
true The arm is fully lowered, the sensor is tripped 
.PP
false Sensor is not tripped 
.RE
.PP

.PP
Definition at line 43 of file Arm\&.cpp\&.
.SS "void Arm::InitDefaultCommand ()\fC [override]\fP"

.PP
Initalizes the default command for this subsystem (\fBArm\fP) 
.PP
Definition at line 32 of file Arm\&.cpp\&.
.SS "void Arm::MoveArm (double Speed)"

.PP
Move \fBArm\fP arm up or down\&. 
.PP
\fBParameters:\fP
.RS 4
\fISpeed\fP speed (from -1 to 1), where 1 is forward-down 
.RE
.PP

.PP
Definition at line 37 of file Arm\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "frc::DigitalInput* Arm::pArmHall\fC [private]\fP"

.PP
hall effects for arm is lowered enough 
.PP
Definition at line 39 of file Arm\&.h\&.
.SS "can::WPI_TalonSRX* Arm::pArmMotor\fC [private]\fP"

.PP
Pointer for \fBArm\fP arm motor\&. 
.PP
Definition at line 36 of file Arm\&.h\&.
.SS "can::WPI_TalonSRX* Arm::pArmMotor2\fC [private]\fP"

.PP
Pointer for \fBArm\fP arm motor\&. 
.PP
Definition at line 37 of file Arm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
