.TH "src/main/include/Subsystems/Arm.h" 3 "Mon Apr 8 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Subsystems/Arm.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <frc/commands/Subsystem\&.h>\fP
.br
\fC#include <frc/DigitalInput\&.h>\fP
.br
\fC#include <frc/WPILib\&.h>\fP
.br
\fC#include <frc/Spark\&.h>\fP
.br
\fC#include <frc/AnalogInput\&.h>\fP
.br
\fC#include <frc/PWMVictorSPX\&.h>\fP
.br
\fC#include <ctre/Phoenix\&.h>\fP
.br
\fC#include 'RobotMap\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArm\fP"
.br
.RI "A subsystem that controls the \fBArm\fP of the robot\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
