.TH "buildcml.py" 3 "Fri Jan 11 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buildcml.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbuildcml\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbuildcml\&.infile\fP = sys\&.argv[1]"
.br
.ti -1c
.RI "string \fBbuildcml\&.outfile_md\fP = 'docs/' + infile\&.split('\&.')[0] + '\&.md'"
.br
.ti -1c
.RI "string \fBbuildcml\&.outfile_txt\fP = infile\&.split('\&.')[0] + '\&.txt'"
.br
.ti -1c
.RI "string \fBbuildcml\&.md_buffer\fP = '# Controller Layouts\\n'"
.br
.ti -1c
.RI "string \fBbuildcml\&.txt_buffer\fP = ''"
.br
.ti -1c
.RI "\fBbuildcml\&.cml\fP = eval(f\&.read())"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
