.TH "buildcml" 3 "Tue Feb 12 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buildcml
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBinfile\fP = sys\&.argv[1]"
.br
.ti -1c
.RI "string \fBoutfile_md\fP = 'docs/' + infile\&.split('\&.')[0] + '\&.md'"
.br
.ti -1c
.RI "string \fBoutfile_txt\fP = infile\&.split('\&.')[0] + '\&.txt'"
.br
.ti -1c
.RI "string \fBmd_buffer\fP = '# Controller Layouts\\n'"
.br
.ti -1c
.RI "string \fBtxt_buffer\fP = ''"
.br
.ti -1c
.RI "\fBcml\fP = eval(f\&.read())"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "buildcml\&.cml = eval(f\&.read())"

.PP
Definition at line 18 of file buildcml\&.py\&.
.SS "buildcml\&.infile = sys\&.argv[1]"

.PP
Definition at line 7 of file buildcml\&.py\&.
.SS "string buildcml\&.md_buffer = '# Controller Layouts\\n'"

.PP
Definition at line 14 of file buildcml\&.py\&.
.SS "string buildcml\&.outfile_md = 'docs/' + infile\&.split('\&.')[0] + '\&.md'"

.PP
Definition at line 10 of file buildcml\&.py\&.
.SS "string buildcml\&.outfile_txt = infile\&.split('\&.')[0] + '\&.txt'"

.PP
Definition at line 11 of file buildcml\&.py\&.
.SS "string buildcml\&.txt_buffer = ''"

.PP
Definition at line 15 of file buildcml\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
