.TH "src/main/include/Subsystems/Compressor.h" 3 "Tue Mar 5 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Subsystems/Compressor.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Subsystem\&.h>\fP
.br
\fC#include 'RobotMap\&.h'\fP
.br
\fC#include <Commands/ControlCompressor\&.h>\fP
.br
\fC#include <frc/Compressor\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcCompressor\fP"
.br
.RI "A subsystem that interfaces with the robot's \fBcCompressor\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
