.TH "src/main/include/Commands/ControlLight.h" 3 "Tue Mar 12 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Commands/ControlLight.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Command\&.h>\fP
.br
\fC#include <Subsystems/Light\&.h>\fP
.br
\fC#include 'RobotMap\&.h'\fP
.br
\fC#include <frc/WPILib\&.h>\fP
.br
\fC#include <frc/GenericHID\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBControlLight\fP"
.br
.RI "An interface command for toggleing the gripper\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
