.TH "src/main/include/Commands/ControlCargo.h" 3 "Tue Mar 5 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Commands/ControlCargo.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Command\&.h>\fP
.br
\fC#include <Subsystems/Flap\&.h>\fP
.br
\fC#include 'RobotMap\&.h'\fP
.br
\fC#include <frc/GenericHID\&.h>\fP
.br
\fC#include <frc/XboxController\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBControlCargo\fP"
.br
.RI "An interface command for driving the robot with an xbox controller\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
