.TH "src/main/cpp/Commands/ControlHatchGripper.cpp" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/cpp/Commands/ControlHatchGripper.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Commands/ControlHatchGripper\&.h'\fP
.br
\fC#include 'Utils/EdgeLight\&.h'\fP
.br
\fC#include 'Robot\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
