.TH "ControlHatchGripper" 3 "Tue Mar 12 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ControlHatchGripper \- An interface command for toggleing the gripper\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ControlHatchGripper\&.h>\fP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControlHatchGripper\fP ()"
.br
.RI "Class constructor\&. "
.ti -1c
.RI "void \fBInitialize\fP () override"
.br
.RI "Runs once on initalization\&. "
.ti -1c
.RI "void \fBExecute\fP () override"
.br
.RI "Called in a loop during Teleop\&. "
.ti -1c
.RI "bool \fBIsFinished\fP () override"
.br
.ti -1c
.RI "void \fBEnd\fP () override"
.br
.RI "Runs once when \fBIsFinished()\fP returns true\&. "
.ti -1c
.RI "void \fBInterrupted\fP () override"
.br
.RI "Runs once if the command is forced to stop\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBspeed\fP"
.br
.ti -1c
.RI "frc::XboxController * \fBpJoyOp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An interface command for toggleing the gripper\&. 
.PP
Definition at line 11 of file ControlHatchGripper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ControlHatchGripper::ControlHatchGripper ()"

.PP
Class constructor\&. 
.PP
Definition at line 5 of file ControlHatchGripper\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ControlHatchGripper::End ()\fC [override]\fP"

.PP
Runs once when \fBIsFinished()\fP returns true\&. 
.PP
Definition at line 32 of file ControlHatchGripper\&.cpp\&.
.SS "void ControlHatchGripper::Execute ()\fC [override]\fP"

.PP
Called in a loop during Teleop\&. 
.PP
Definition at line 16 of file ControlHatchGripper\&.cpp\&.
.SS "void ControlHatchGripper::Initialize ()\fC [override]\fP"

.PP
Runs once on initalization\&. 
.PP
Definition at line 13 of file ControlHatchGripper\&.cpp\&.
.SS "void ControlHatchGripper::Interrupted ()\fC [override]\fP"

.PP
Runs once if the command is forced to stop\&. 
.PP
Definition at line 36 of file ControlHatchGripper\&.cpp\&.
.SS "bool ControlHatchGripper::IsFinished ()\fC [override]\fP"

.PP
Definition at line 29 of file ControlHatchGripper\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "frc::XboxController* ControlHatchGripper::pJoyOp\fC [private]\fP"

.PP
Definition at line 22 of file ControlHatchGripper\&.h\&.
.SS "double ControlHatchGripper::speed\fC [private]\fP"

.PP
Definition at line 21 of file ControlHatchGripper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
