.TH "CrawlDrive" 3 "Tue Mar 5 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CrawlDrive \- A subsytem that interfaces with the climberbase on the robot\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CrawlDrive\&.h>\fP
.PP
Inherits Subsystem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrawlDrive\fP ()"
.br
.RI "Class constructor\&. "
.ti -1c
.RI "void \fBInitDefaultCommand\fP () override"
.br
.RI "Initalizes the default command for this subsystem () "
.ti -1c
.RI "void \fBMove\fP (double Speed)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "frc::Spark * \fBpCrawlLeft\fP"
.br
.RI "Pointer for the left crawl motor\&. "
.ti -1c
.RI "frc::Spark * \fBpCrawlRight\fP"
.br
.RI "Pointer for the right crawl motor\&. "
.in -1c
.SH "Detailed Description"
.PP 
A subsytem that interfaces with the climberbase on the robot\&. 
.PP
Definition at line 10 of file CrawlDrive\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CrawlDrive::CrawlDrive ()"

.PP
Class constructor\&. 
.PP
Definition at line 3 of file CrawlDrive\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CrawlDrive::InitDefaultCommand ()\fC [override]\fP"

.PP
Initalizes the default command for this subsystem () 
.PP
Definition at line 20 of file CrawlDrive\&.cpp\&.
.SS "void CrawlDrive::Move (double Speed)"
Pass data to wpilib's ArcadeDrive
.PP
\fBParameters:\fP
.RS 4
\fIxSpeed\fP Forward speed (form -1 to 1) 
.br
\fIzRotation\fP Rotation (from -1 to 1) 
.RE
.PP

.PP
Definition at line 24 of file CrawlDrive\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "frc::Spark* CrawlDrive::pCrawlLeft\fC [private]\fP"

.PP
Pointer for the left crawl motor\&. 
.PP
Definition at line 24 of file CrawlDrive\&.h\&.
.SS "frc::Spark* CrawlDrive::pCrawlRight\fC [private]\fP"

.PP
Pointer for the right crawl motor\&. 
.PP
Definition at line 25 of file CrawlDrive\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
