.TH "CrawlDrive" 3 "Mon Apr 8 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CrawlDrive \- A subsytem that interfaces with the climberbase on the robot\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CrawlDrive\&.h>\fP
.PP
Inherits Subsystem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrawlDrive\fP ()"
.br
.RI "Class constructor\&. "
.ti -1c
.RI "void \fBInitDefaultCommand\fP () override"
.br
.RI "Initalizes the default command for this subsystem () "
.ti -1c
.RI "void \fBMove\fP (double Speed)"
.br
.RI "Drive, (or crawl), forwards or backwards Moves the wheels attached to the arms\&. What wheels do\&. "
.ti -1c
.RI "bool \fBGetSensor\fP (void)"
.br
.RI "Returns true if its on the floor\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "frc::Spark * \fBpCrawlLeft\fP"
.br
.RI "Pointer for the left crawl motor\&. "
.ti -1c
.RI "frc::Spark * \fBpCrawlRight\fP"
.br
.RI "Pointer for the right crawl motor\&. "
.ti -1c
.RI "frc::DigitalInput * \fBpFloorSensor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A subsytem that interfaces with the climberbase on the robot\&. 
.PP
Definition at line 11 of file CrawlDrive\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CrawlDrive::CrawlDrive ()"

.PP
Class constructor\&. 
.PP
Definition at line 3 of file CrawlDrive\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CrawlDrive::GetSensor (void)"

.PP
Returns true if its on the floor\&. 
.PP
\fBReturns:\fP
.RS 4
true Something is right in front of it (on the floor) 
.PP
false Nothing in front of it (in the air) 
.RE
.PP

.PP
Definition at line 27 of file CrawlDrive\&.cpp\&.
.SS "void CrawlDrive::InitDefaultCommand ()\fC [override]\fP"

.PP
Initalizes the default command for this subsystem () 
.PP
Definition at line 23 of file CrawlDrive\&.cpp\&.
.SS "void CrawlDrive::Move (double Speed)"

.PP
Drive, (or crawl), forwards or backwards Moves the wheels attached to the arms\&. What wheels do\&. 
.PP
\fBParameters:\fP
.RS 4
\fISpeed\fP Percent power to go\&. 100% drives forwards 
.RE
.PP

.PP
Definition at line 32 of file CrawlDrive\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "frc::Spark* CrawlDrive::pCrawlLeft\fC [private]\fP"

.PP
Pointer for the left crawl motor\&. 
.PP
Definition at line 31 of file CrawlDrive\&.h\&.
.SS "frc::Spark* CrawlDrive::pCrawlRight\fC [private]\fP"

.PP
Pointer for the right crawl motor\&. 
.PP
Definition at line 32 of file CrawlDrive\&.h\&.
.SS "frc::DigitalInput* CrawlDrive::pFloorSensor\fC [private]\fP"

.PP
Definition at line 33 of file CrawlDrive\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
