.TH "src/main/include/Commands/DeployLeg.h" 3 "Mon Feb 4 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Commands/DeployLeg.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/TimedCommand\&.h>\fP
.br
\fC#include <Subsystems/Leg\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeployLeg\fP"
.br
.RI "An interface command for activating the Pull \fBArm\fP on the robot\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
