.TH "src/main/include/Subsystems/DriveTrain.h" 3 "Tue Feb 12 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Subsystems/DriveTrain.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Subsystem\&.h>\fP
.br
\fC#include <frc/WPILib\&.h>\fP
.br
\fC#include <ctre/Phoenix\&.h>\fP
.br
\fC#include <frc/drive/DifferentialDrive\&.h>\fP
.br
\fC#include 'RobotMap\&.h'\fP
.br
\fC#include <Commands/DriveWithJoystick\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDriveTrain\fP"
.br
.RI "A subsystem that interfaces with the drivebase on the robot\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
