.TH "src/main/include/Commands/DriveWithJoystick.h" 3 "Sun Feb 3 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Commands/DriveWithJoystick.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Command\&.h>\fP
.br
\fC#include <Subsystems/DriveTrain\&.h>\fP
.br
\fC#include 'RobotMap\&.h'\fP
.br
\fC#include <frc/GenericHID\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDriveWithJoystick\fP"
.br
.RI "An interface command for driving the robot with an xbox controller\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
