.TH "DriveWithJoystick" 3 "Sat Jan 26 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DriveWithJoystick \- An interface command for driving the robot with an xbox controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DriveWithJoystick\&.h>\fP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDriveWithJoystick\fP ()"
.br
.RI "Class constructor\&. "
.ti -1c
.RI "void \fBInitialize\fP () override"
.br
.RI "Runs once on initalization\&. "
.ti -1c
.RI "void \fBExecute\fP () override"
.br
.RI "Called in a loop during Teleop\&. "
.ti -1c
.RI "bool \fBIsFinished\fP () override"
.br
.ti -1c
.RI "void \fBEnd\fP () override"
.br
.RI "Runs once when \fBIsFinished()\fP returns true\&. "
.ti -1c
.RI "void \fBInterrupted\fP () override"
.br
.RI "Runs once if the command is forced to stop\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBgetTriggers\fP ()"
.br
.RI "Called only if the drivemode is set to 1\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBdirectionMultiplier\fP"
.br
.RI "Can be 1 or -1\&. Determines the direction the the robot moves in\&. "
.ti -1c
.RI "double \fBmagnitudeMultiplier\fP"
.br
.RI "The magnitude of the robot is multiplied by this number\&. Used for slowmode\&. "
.ti -1c
.RI "double \fBmagnitude\fP"
.br
.RI "magnitude value that will be passed into \fBDriveTrain::RadialDrive\fP "
.ti -1c
.RI "double \fBradial\fP"
.br
.RI "radial value that will be passed into \fBDriveTrain::RadialDrive\fP "
.ti -1c
.RI "int \fBdriveMode\fP"
.br
.RI "Used to keep track of the drive mode\&. "
.ti -1c
.RI "frc::XboxController * \fBpJoyDrive\fP"
.br
.RI "A mnemonic for the driver's controller because we are lazy\&. "
.in -1c
.SH "Detailed Description"
.PP 
An interface command for driving the robot with an xbox controller\&. 
.PP
Definition at line 10 of file DriveWithJoystick\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DriveWithJoystick::DriveWithJoystick ()"

.PP
Class constructor\&. 
.PP
Definition at line 4 of file DriveWithJoystick\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DriveWithJoystick::End ()\fC [override]\fP"

.PP
Runs once when \fBIsFinished()\fP returns true\&. 
.PP
Definition at line 74 of file DriveWithJoystick\&.cpp\&.
.SS "void DriveWithJoystick::Execute ()\fC [override]\fP"

.PP
Called in a loop during Teleop\&. 
.PP
Definition at line 43 of file DriveWithJoystick\&.cpp\&.
.SS "bool DriveWithJoystick::getTriggers ()\fC [inline]\fP, \fC [private]\fP"

.PP
Called only if the drivemode is set to 1\&. 
.PP
Definition at line 34 of file DriveWithJoystick\&.cpp\&.
.SS "void DriveWithJoystick::Initialize ()\fC [override]\fP"

.PP
Runs once on initalization\&. 
.PP
Definition at line 12 of file DriveWithJoystick\&.cpp\&.
.SS "void DriveWithJoystick::Interrupted ()\fC [override]\fP"

.PP
Runs once if the command is forced to stop\&. 
.PP
Definition at line 78 of file DriveWithJoystick\&.cpp\&.
.SS "bool DriveWithJoystick::IsFinished ()\fC [override]\fP"
Used to tell wpilib if the command is fully finished\&. This should never return true Because we always want to be able to drive the bot during teleop
.PP
\fBReturns:\fP
.RS 4
True if command is finished, else false 
.RE
.PP

.PP
Definition at line 71 of file DriveWithJoystick\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int DriveWithJoystick::directionMultiplier\fC [private]\fP"

.PP
Can be 1 or -1\&. Determines the direction the the robot moves in\&. 
.PP
Definition at line 28 of file DriveWithJoystick\&.h\&.
.SS "int DriveWithJoystick::driveMode\fC [private]\fP"

.PP
Used to keep track of the drive mode\&. driveMode is set depending on what is selected from drivermenu
.PP
0 = Joystick 1 = Triggers 
.PP
Definition at line 42 of file DriveWithJoystick\&.h\&.
.SS "double DriveWithJoystick::magnitude\fC [private]\fP"

.PP
magnitude value that will be passed into \fBDriveTrain::RadialDrive\fP 
.PP
Definition at line 31 of file DriveWithJoystick\&.h\&.
.SS "double DriveWithJoystick::magnitudeMultiplier\fC [private]\fP"

.PP
The magnitude of the robot is multiplied by this number\&. Used for slowmode\&. 
.PP
Definition at line 29 of file DriveWithJoystick\&.h\&.
.SS "frc::XboxController* DriveWithJoystick::pJoyDrive\fC [private]\fP"

.PP
A mnemonic for the driver's controller because we are lazy\&. 
.PP
Definition at line 44 of file DriveWithJoystick\&.h\&.
.SS "double DriveWithJoystick::radial\fC [private]\fP"

.PP
radial value that will be passed into \fBDriveTrain::RadialDrive\fP 
.PP
Definition at line 32 of file DriveWithJoystick\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
