.TH "src/main/include/Subsystems/Leg.h" 3 "Mon Apr 8 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Subsystems/Leg.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Subsystem\&.h>\fP
.br
\fC#include <frc/DigitalInput\&.h>\fP
.br
\fC#include <frc/WPILib\&.h>\fP
.br
\fC#include <ctre/Phoenix\&.h>\fP
.br
\fC#include 'RobotMap\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeg\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
