.TH "src/main/include/Subsystems/Light.h" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Subsystems/Light.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Subsystem\&.h>\fP
.br
\fC#include 'RobotMap\&.h'\fP
.br
\fC#include <Commands/ControlLight\&.h>\fP
.br
\fC#include <frc/Solenoid\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLight\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
