.TH "md_docs_controller_layout" 3 "Fri Jan 11 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_controller_layout \- Driver 
Type: Xbox Controller
.PP
Port: 0 Joysticks  Left  X  \fBRobot\fP steering / rotation   Y  Btn  Right  X  Y  Btn  Dpad  Up  Down  Left  Right  Button Pad  A  \fBRobot\fP vision alignment (hold)   B  X  Flip forward and backward (toggle)   Y  Triggers  Left  \fBRobot\fP backwards   Right  \fBRobot\fP forwards   Bumpers  Left  Right  Slow mode (hold)   Other  Start  Select  Home  
.SH "Operator"
.PP
.PP
Type: Xbox Controller
.PP
Port: 1 Joysticks  Left  X  Y  Btn  Right  X  Y  Btn  Dpad  Up  Down  Left  Right  Button Pad  A  B  X  Y  Triggers  Left  Right  Bumpers  Left  Right  Other  Start  Select  Home  
