.TH "md_docs_controller_layout" 3 "Mon Feb 4 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_controller_layout \- Controller Layouts 

.SS "Driver"
.PP
Type: Xbox Controller
.PP
Port: 0 Joysticks  --   Left  --   X  \fBRobot\fP steering / rotation   Y  Btn  Right  --   X  Y  Btn  Dpad  --   Up  Down  Left  Right  Button Pad  --   A  \fBRobot\fP vision alignment (hold)   B  X  Flip forward and backward (toggle)   Y  Triggers  --   Left  \fBRobot\fP backwards   Right  \fBRobot\fP forwards   Bumpers  --   Left  Right  Slow mode (hold)   Other  --   Start  Select  Home  
.SS "Operator"
.PP
Type: Xbox Controller
.PP
Port: 1 Joysticks  --   Left  --   X  Move slider   Y  Btn  Right  --   X  Y  Btn  Dpad  --   Up  Down  Left  Right  Button Pad  --   A  B  X  Y  Triggers  --   Left  Right  Bumpers  --   Left  Right  Other  --   Start  Select  Home  
