.TH "md_VisionMode_README" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_VisionMode_READMECameraTuner 
 \- A tool for building field-specific JSON config files without a robot
.PP
.SS "Setup"
.PP
Setup is simple\&. Make sure you have installed \fCopencv-python\fP and \fCnumpy\fP Then, just run this command: 
.PP
.nf
pip3 install -r requirementx\&.txt

.fi
.PP
.PP
.SS "Configuration"
.PP
To change the active camera, change the camera path in \fCfrc\&.json\fP
.PP
.SS "Running"
.PP
Just run: 
.PP
.nf
python3 CameraTuner

.fi
.PP
 
