.TH "src/main/include/OI.h" 3 "Mon Apr 8 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/OI.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/WPILib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOI\fP"
.br
.RI "Operator Interface allows various commands to access the xbox controllers through the DriverStation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
