.TH "src/main/include/OI.h" 3 "Sun Dec 9 2018" "BaseBot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/OI.h
.SH SYNOPSIS
.br
.PP
\fC#include <WPILib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOI\fP"
.br
.RI "Operator Interface allows various commands to access the xbox controllers through the DriverStation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BaseBot from the source code\&.
