.TH "src/main/include/RobotMap.h" 3 "Tue Mar 5 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/RobotMap.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAMERASERVER_DRIVER_CAMERA\fP   1"
.br
.ti -1c
.RI "#define \fBCAMERASERVER_VISION_CAMERA\fP   0"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_LEFT_FRONT_MOTOR\fP   1"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_LEFT_REAR_MOTOR\fP   2"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RIGHT_FRONT_MOTOR\fP   3"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RIGHT_REAR_MOTOR\fP   4"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_LEFT_FRONT_MOTOR_INVERT\fP   false"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_LEFT_REAR_MOTOR_INVERT\fP   false"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RIGHT_FRONT_MOTOR_INVERT\fP   true"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RIGHT_REAR_MOTOR_INVERT\fP   true"
.br
.ti -1c
.RI "#define \fBXBOX_DEADZONE_RIGHT_JOY\fP   0\&.1"
.br
.ti -1c
.RI "#define \fBXBOX_DEADZONE_LEFT_JOY\fP   0\&.1"
.br
.ti -1c
.RI "#define \fBCLIMB_ARM_MOTOR\fP   5"
.br
.ti -1c
.RI "#define \fBCLIMB_ARM_MOTOR_2\fP   6"
.br
.ti -1c
.RI "#define \fBCLIMB_LEG_MOTOR\fP   8"
.br
.ti -1c
.RI "#define \fBCRAWL_LEFT_MOTOR\fP   1"
.br
.ti -1c
.RI "#define \fBCRAWL_RIGHT_MOTOR\fP   0"
.br
.ti -1c
.RI "#define \fBCLIMB_ULTRASONIC\fP   1"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RADIAL_SENSITIVITY_CUTOFF\fP   0\&.8"
.br
.ti -1c
.RI "#define \fBSLIDER_MOTOR\fP   7"
.br
.ti -1c
.RI "#define \fBPCM_CAN_ID\fP   11"
.br
.ti -1c
.RI "#define \fBPISTON_ID\fP   7"
.br
.ti -1c
.RI "#define \fBLIGHT_ID\fP   0"
.br
.ti -1c
.RI "#define \fBHatchGripper_FORWARD_ID\fP   1"
.br
.ti -1c
.RI "#define \fBHatchGripper_REVERSE_ID\fP   2"
.br
.ti -1c
.RI "#define \fBFLAP_ID_FORWARD\fP   5"
.br
.ti -1c
.RI "#define \fBFLAP_ID_REVERSE\fP   6"
.br
.ti -1c
.RI "#define \fBDRIVEWITHJOYSTICK_ROTATION_LIMITER\fP   0\&.95"
.br
.ti -1c
.RI "#define \fBXBOX_CONTROLLER_DRIVE_PORT\fP   0"
.br
.ti -1c
.RI "#define \fBXBOX_CONTROLLER_OPERATOR_PORT\fP   1"
.br
.ti -1c
.RI "#define \fBXBOX_CONTROLLER_DEBUG_PORT\fP   2"
.br
.ti -1c
.RI "#define \fBFalse\fP   false"
.br
.ti -1c
.RI "#define \fBTrue\fP   true"
.br
.ti -1c
.RI "#define \fBelif\fP   else if"
.br
.ti -1c
.RI "#define \fBHand\fP   frc::GenericHID::JoystickHand"
.br
.ti -1c
.RI "#define \fBWinGame\fP(_class_)   frc::StartRobot<_class_>()"
.br
.ti -1c
.RI "#define \fBHeader\fP(x)   std::cout << x"
.br
.ti -1c
.RI "#define \fBEndHeader\fP()   std::cout << 'DONE' << std::endl"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAMERASERVER_DRIVER_CAMERA   1"
The RobotMap is a mapping from the ports sensors and actuators are wired into to a variable name\&. This provides flexibility changing wiring, makes checking the wiring easier and significantly reduces the number of magic numbers floating around\&. 
.PP
Definition at line 14 of file RobotMap\&.h\&.
.SS "#define CAMERASERVER_VISION_CAMERA   0"

.PP
Definition at line 15 of file RobotMap\&.h\&.
.SS "#define CLIMB_ARM_MOTOR   5"

.PP
Definition at line 34 of file RobotMap\&.h\&.
.SS "#define CLIMB_ARM_MOTOR_2   6"

.PP
Definition at line 36 of file RobotMap\&.h\&.
.SS "#define CLIMB_LEG_MOTOR   8"

.PP
Definition at line 37 of file RobotMap\&.h\&.
.SS "#define CLIMB_ULTRASONIC   1"

.PP
Definition at line 43 of file RobotMap\&.h\&.
.SS "#define CRAWL_LEFT_MOTOR   1"

.PP
Definition at line 39 of file RobotMap\&.h\&.
.SS "#define CRAWL_RIGHT_MOTOR   0"

.PP
Definition at line 40 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_LEFT_FRONT_MOTOR   1"

.PP
Definition at line 18 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_LEFT_FRONT_MOTOR_INVERT   false"

.PP
Definition at line 24 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_LEFT_REAR_MOTOR   2"

.PP
Definition at line 19 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_LEFT_REAR_MOTOR_INVERT   false"

.PP
Definition at line 25 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RADIAL_SENSITIVITY_CUTOFF   0\&.8"

.PP
Definition at line 44 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RIGHT_FRONT_MOTOR   3"

.PP
Definition at line 20 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RIGHT_FRONT_MOTOR_INVERT   true"

.PP
Definition at line 26 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RIGHT_REAR_MOTOR   4"

.PP
Definition at line 21 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RIGHT_REAR_MOTOR_INVERT   true"

.PP
Definition at line 27 of file RobotMap\&.h\&.
.SS "#define DRIVEWITHJOYSTICK_ROTATION_LIMITER   0\&.95"

.PP
Definition at line 65 of file RobotMap\&.h\&.
.SS "#define elif   else if"

.PP
Definition at line 75 of file RobotMap\&.h\&.
.SS "#define EndHeader()   std::cout << 'DONE' << std::endl"

.PP
Definition at line 84 of file RobotMap\&.h\&.
.SS "#define False   false"

.PP
Definition at line 73 of file RobotMap\&.h\&.
.SS "#define FLAP_ID_FORWARD   5"

.PP
Definition at line 61 of file RobotMap\&.h\&.
.SS "#define FLAP_ID_REVERSE   6"

.PP
Definition at line 62 of file RobotMap\&.h\&.
.SS "#define Hand   frc::GenericHID::JoystickHand"

.PP
Definition at line 78 of file RobotMap\&.h\&.
.SS "#define HatchGripper_FORWARD_ID   1"

.PP
Definition at line 58 of file RobotMap\&.h\&.
.SS "#define HatchGripper_REVERSE_ID   2"

.PP
Definition at line 59 of file RobotMap\&.h\&.
.SS "#define Header(x)   std::cout << x"

.PP
Definition at line 83 of file RobotMap\&.h\&.
.SS "#define LIGHT_ID   0"

.PP
Definition at line 55 of file RobotMap\&.h\&.
.SS "#define PCM_CAN_ID   11"

.PP
Definition at line 50 of file RobotMap\&.h\&.
.SS "#define PISTON_ID   7"

.PP
Definition at line 52 of file RobotMap\&.h\&.
.SS "#define SLIDER_MOTOR   7"

.PP
Definition at line 47 of file RobotMap\&.h\&.
.SS "#define True   true"

.PP
Definition at line 74 of file RobotMap\&.h\&.
.SS "#define WinGame(_class_)   frc::StartRobot<_class_>()"

.PP
Definition at line 81 of file RobotMap\&.h\&.
.SS "#define XBOX_CONTROLLER_DEBUG_PORT   2"

.PP
Definition at line 70 of file RobotMap\&.h\&.
.SS "#define XBOX_CONTROLLER_DRIVE_PORT   0"

.PP
Definition at line 68 of file RobotMap\&.h\&.
.SS "#define XBOX_CONTROLLER_OPERATOR_PORT   1"

.PP
Definition at line 69 of file RobotMap\&.h\&.
.SS "#define XBOX_DEADZONE_LEFT_JOY   0\&.1"

.PP
Definition at line 31 of file RobotMap\&.h\&.
.SS "#define XBOX_DEADZONE_RIGHT_JOY   0\&.1"

.PP
Definition at line 30 of file RobotMap\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
