.TH "src/main/cpp/Robot.cpp" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/cpp/Robot.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Robot\&.h'\fP
.br
\fC#include <frc/commands/Scheduler\&.h>\fP
.br
\fC#include <frc/smartdashboard/SmartDashboard\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'Utils/EdgeLight\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLog\fP (std::string message)"
.br
.RI "Main robot class that is called by wpilib\&. "
.ti -1c
.RI "void \fBvector_print\fP (std::vector< std::string > const &input)"
.br
.ti -1c
.RI "void \fBDisplay\fP (clock_t start, clock_t current)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBlogBuffer\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Display (clock_t start, clock_t current)"

.PP
Definition at line 40 of file Robot\&.cpp\&.
.SS "void Log (std::string message)"

.PP
Main robot class that is called by wpilib\&. 
.PP
Definition at line 29 of file Robot\&.cpp\&.
.SS "int main ()"

.PP
Definition at line 288 of file Robot\&.cpp\&.
.SS "void vector_print (std::vector< std::string > const & input)"

.PP
Definition at line 33 of file Robot\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "std::vector<std::string> logBuffer"

.PP
Definition at line 27 of file Robot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
