.TH "src/main/include/Robot.h" 3 "Mon Apr 8 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Robot.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Command\&.h>\fP
.br
\fC#include <frc/smartdashboard/SendableChooser\&.h>\fP
.br
\fC#include <frc/TimedRobot\&.h>\fP
.br
\fC#include <frc/WPILib\&.h>\fP
.br
\fC#include <cscore_oo\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <networktables/NetworkTable\&.h>\fP
.br
\fC#include 'Commands/TriggerDrive\&.h'\fP
.br
\fC#include 'Commands/ControlCompressor\&.h'\fP
.br
\fC#include 'Commands/PullArm\&.h'\fP
.br
\fC#include 'Commands/PullLeg\&.h'\fP
.br
\fC#include 'Autonomous/AutoClimbHigh\&.h'\fP
.br
\fC#include 'Commands/ClimbManager\&.h'\fP
.br
\fC#include 'Commands/ControlHatchGripper\&.h'\fP
.br
\fC#include 'Commands/ControlLight\&.h'\fP
.br
\fC#include 'Commands/Climb\&.h'\fP
.br
\fC#include 'Commands/ControlSlider\&.h'\fP
.br
\fC#include 'Commands/ControlCargo\&.h'\fP
.br
\fC#include 'OI\&.h'\fP
.br
\fC#include 'Subsystems/DriveTrain\&.h'\fP
.br
\fC#include 'Subsystems/CrawlDrive\&.h'\fP
.br
\fC#include 'Subsystems/Arm\&.h'\fP
.br
\fC#include 'Subsystems/Leg\&.h'\fP
.br
\fC#include 'Subsystems/Slider\&.h'\fP
.br
\fC#include 'Subsystems/Compressor\&.h'\fP
.br
\fC#include 'Subsystems/Piston\&.h'\fP
.br
\fC#include 'Subsystems/HatchGripper\&.h'\fP
.br
\fC#include 'Subsystems/Flap\&.h'\fP
.br
\fC#include 'Subsystems/Light\&.h'\fP
.br
\fC#include <frc/PowerDistributionPanel\&.h>\fP
.br
\fC#include <frc/DriverStation\&.h>\fP
.br
\fC#include 'AHRS\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRobot\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLog\fP (std::string msg)"
.br
.RI "Main robot class that is called by wpilib\&. "
.ti -1c
.RI "void \fBDisplay\fP (clock_t start, clock_t current)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Display (clock_t start, clock_t current)"

.PP
Definition at line 20 of file logging\&.cpp\&.
.SS "void Log (std::string msg)"

.PP
Main robot class that is called by wpilib\&. 
.PP
Definition at line 9 of file logging\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
