.TH "src/main/include/RobotMap.h" 3 "Wed Dec 5 2018" "BaseBot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/RobotMap.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDRIVETRAIN_LEFT_FRONT_MOTOR\fP   5"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_LEFT_REAR_MOTOR\fP   6"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RIGHT_FRONT_MOTOR\fP   4"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RIGHT_REAR_MOTOR\fP   3"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_LEFT_FRONT_MOTOR_INVERT\fP   false"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_LEFT_REAR_MOTOR_INVERT\fP   false"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RIGHT_FRONT_MOTOR_INVERT\fP   true"
.br
.ti -1c
.RI "#define \fBDRIVETRAIN_RIGHT_REAR_MOTOR_INVERT\fP   true"
.br
.ti -1c
.RI "#define \fBXBOX_CONTROLLER_DRIVE_PORT\fP   0"
.br
.ti -1c
.RI "#define \fBXBOX_CONTROLLER_OPERATOR_PORT\fP   1"
.br
.ti -1c
.RI "#define \fBFalse\fP   false"
.br
.ti -1c
.RI "#define \fBTrue\fP   true"
.br
.ti -1c
.RI "#define \fBelif\fP   else if"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DRIVETRAIN_LEFT_FRONT_MOTOR   5"
The RobotMap is a mapping from the ports sensors and actuators are wired into to a variable name\&. This provides flexibility changing wiring, makes checking the wiring easier and significantly reduces the number of magic numbers floating around\&. 
.PP
Definition at line 14 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_LEFT_FRONT_MOTOR_INVERT   false"

.PP
Definition at line 20 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_LEFT_REAR_MOTOR   6"

.PP
Definition at line 15 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_LEFT_REAR_MOTOR_INVERT   false"

.PP
Definition at line 21 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RIGHT_FRONT_MOTOR   4"

.PP
Definition at line 16 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RIGHT_FRONT_MOTOR_INVERT   true"

.PP
Definition at line 22 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RIGHT_REAR_MOTOR   3"

.PP
Definition at line 17 of file RobotMap\&.h\&.
.SS "#define DRIVETRAIN_RIGHT_REAR_MOTOR_INVERT   true"

.PP
Definition at line 23 of file RobotMap\&.h\&.
.SS "#define elif   else if"

.PP
Definition at line 32 of file RobotMap\&.h\&.
.SS "#define False   false"

.PP
Definition at line 30 of file RobotMap\&.h\&.
.SS "#define True   true"

.PP
Definition at line 31 of file RobotMap\&.h\&.
.SS "#define XBOX_CONTROLLER_DRIVE_PORT   0"

.PP
Definition at line 26 of file RobotMap\&.h\&.
.SS "#define XBOX_CONTROLLER_OPERATOR_PORT   1"

.PP
Definition at line 27 of file RobotMap\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BaseBot from the source code\&.
