.TH "src/main/include/Robot.h" 3 "Tue Feb 12 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Robot.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/commands/Command\&.h>\fP
.br
\fC#include <frc/smartdashboard/SendableChooser\&.h>\fP
.br
\fC#include <networktables/NetworkTable\&.h>\fP
.br
\fC#include <frc/TimedRobot\&.h>\fP
.br
\fC#include <frc/WPILib\&.h>\fP
.br
\fC#include <cscore_oo\&.h>\fP
.br
\fC#include 'Commands/TriggerDrive\&.h'\fP
.br
\fC#include 'Commands/ControlCompressor\&.h'\fP
.br
\fC#include 'Commands/testUltra\&.h'\fP
.br
\fC#include 'Commands/PullArm\&.h'\fP
.br
\fC#include 'Commands/PullLeg\&.h'\fP
.br
\fC#include 'Commands/DeployClimb\&.h'\fP
.br
\fC#include 'OI\&.h'\fP
.br
\fC#include 'Subsystems/DriveTrain\&.h'\fP
.br
\fC#include 'Subsystems/CrawlDrive\&.h'\fP
.br
\fC#include 'Subsystems/Arm\&.h'\fP
.br
\fC#include 'Subsystems/Leg\&.h'\fP
.br
\fC#include 'Commands/ControlSlider\&.h'\fP
.br
\fC#include 'Subsystems/Slider\&.h'\fP
.br
\fC#include 'Subsystems/Compressor\&.h'\fP
.br
\fC#include 'Subsystems/Piston\&.h'\fP
.br
\fC#include <frc/PowerDistributionPanel\&.h>\fP
.br
\fC#include <frc/DriverStation\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRobot\fP"
.br
.RI "Main robot class that is called by wpilib\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
