.TH "testUltra" 3 "Tue Mar 5 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testUltra \- A command for testing the ultrasonic sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testUltra\&.h>\fP
.PP
Inherits Command\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestUltra\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP () override"
.br
.ti -1c
.RI "void \fBExecute\fP () override"
.br
.ti -1c
.RI "bool \fBIsFinished\fP () override"
.br
.ti -1c
.RI "void \fBEnd\fP () override"
.br
.ti -1c
.RI "void \fBInterrupted\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
A command for testing the ultrasonic sensor\&. 
.PP
Definition at line 11 of file testUltra\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testUltra::testUltra ()"

.PP
Definition at line 12 of file testUltra\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void testUltra::End ()\fC [override]\fP"

.PP
Definition at line 34 of file testUltra\&.cpp\&.
.SS "void testUltra::Execute ()\fC [override]\fP"

.PP
Definition at line 23 of file testUltra\&.cpp\&.
.SS "void testUltra::Initialize ()\fC [override]\fP"

.PP
Definition at line 20 of file testUltra\&.cpp\&.
.SS "void testUltra::Interrupted ()\fC [override]\fP"

.PP
Definition at line 38 of file testUltra\&.cpp\&.
.SS "bool testUltra::IsFinished ()\fC [override]\fP"

.PP
Definition at line 31 of file testUltra\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
