.TH "src/main/include/Utils/TickTime.h" 3 "Fri Jan 11 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/include/Utils/TickTime.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTickTime\fP"
.br
.RI "A simple timer that uses the robot period to track time\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
