.TH "Utils::EdgeLight" 3 "Sun Apr 14 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils::EdgeLight
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPush\fP ()"
.br
.ti -1c
.RI "void \fBAppend\fP (\fBLedColour\fP colour)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBLedColour\fP \fBledbuffer\fP = \fBLedColour::kSOLID_WHITE\fP"
.br
.ti -1c
.RI "frc::Spark * \fBpLEDController\fP = new frc::Spark(\fBLEDCONTROLLER_ID\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Utils::EdgeLight::Append (\fBLedColour\fP colour)"

.PP
Definition at line 7 of file EdgeLight\&.cpp\&.
.SS "void Utils::EdgeLight::Push ()"

.PP
Definition at line 11 of file EdgeLight\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBLedColour\fP Utils::EdgeLight::ledbuffer = \fBLedColour::kSOLID_WHITE\fP"

.PP
Definition at line 4 of file EdgeLight\&.cpp\&.
.SS "frc::Spark * Utils::EdgeLight::pLEDController = new frc::Spark(\fBLEDCONTROLLER_ID\fP)"

.PP
Definition at line 5 of file EdgeLight\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
